In [1]:
from kMeans import kMeans
import numpy as np
# import pandas as pd

In [2]:
# All matrix have to be 2D Arrays Shape (2, ) : array.ndim = 2
x = [1, 1.5, 3, 5, 3.5, 4.5, 3.5, 4, ]  # col 1
y = [1,   2, 4, 7,   5,   5, 4.5, 4, ]  # col 2

In [3]:
# - treating data ---------------------------------------
X_zip = list( zip(x, y) )   # samples : tuple

X = np.array([ row for row in X_zip ])  # @ll rows

In [4]:
# - @Self kMeans model
kmeans = kMeans(k_clusters=2,
                centroidSelectionMethod='randomly',
                iterNbr=5,
                )

"""
# kmeans.fit_(X=np.array([x,y,]), )
kmeans.fit_(X=[np.array(x)[:5], np.array(y)[:5], ], )

kmeans.predict_(X=[np.array(x)[5:], np.array(y)[5:], ], )"""

'\n# kmeans.fit_(X=np.array([x,y,]), )\nkmeans.fit_(X=[np.array(x)[:5], np.array(y)[:5], ], )\n\nkmeans.predict_(X=[np.array(x)[5:], np.array(y)[5:], ], )'

In [5]:
# - Training Model on Data
kmeansTrained = kmeans.fit_(X=X, )
print(f" kmeansTrained : {kmeansTrained} \n")

Centroids :
          init    tUpdated pUpdated
C0  [1.0, 1.0]  [1.0, 1.0]       ()
C1  [1.5, 2.0]  [1.5, 2.0]       ()

 kmeansTrained :
<kMeans.kMeans object at 0x0000022D8F52CC80>
kMeans(k_clusters=2, kDetMethod=None, centroidSelectionMethod=randomly, iterNbr=5)

In [6]:
# - Predicting many Class
predictions = kmeans.predict_(X=np.array([[2, 5, ]], ))
print(f" predictions : {predictions} \n")

 predictions : []

---

In [7]:
df = kmeans.datasetCp
df

       ax1  ax2
data1  1.0  1.0
data2  1.5  2.0
data3  3.0  4.0
data4  5.0  7.0
data5  3.5  5.0
data6  4.5  5.0
data7  3.5  4.5
data8  4.0  4.0

In [11]:
dfRsum = df['ax1'] + df['ax2']
# dfRsum

In [12]:
dfArray = kmeans.XdNDArray
# dfArray

---

In [ ]:
df_ = df.copy(deep=False)
# del df_

In [ ]:
df_1 = df_.copy()
del df_1

       ax1  ax2
data1  1.0  1.0
data2  1.5  2.0
data3  3.0  4.0
data4  5.0  7.0
data5  3.5  5.0
data6  4.5  5.0
data7  3.5  4.5
data8  4.0  4.0

In [30]:
dfcl = kmeans.clusters
dfcl

      name asgPointsLtrs asgPointsCoords
0  Class_0            []              []
1  Class_1            []              []

class SubscriptionDemo:
    def __getitem__(self, key):
        print(f'subscripted with: {key!r}')

demo = SubscriptionDemo()
demo[1]

demo['a' * 3]

In [31]:
dfcl.dtypes

name               object
asgPointsLtrs      object
asgPointsCoords    object
dtype: object

In [13]:
dfcl['asgPointsCoords'][0].append(1)

In [14]:
dfcl

      name asgPointsLtrs asgPointsCoords
0  Class_0            []             [1]
1  Class_1            []              []

---

In [15]:
kmeans.centroids['init']['C1']

[5.0, 7.0]

In [16]:
dfCen = kmeans.centroids
dfCen

          init    tUpdated pUpdated
C0  [4.5, 5.0]  [4.5, 5.0]       ()
C1  [5.0, 7.0]  [5.0, 7.0]       ()

In [17]:
dfCen['tUpdated'].apply(list.append, args=([2]))

C0    None
C1    None
Name: tUpdated, dtype: object

In [18]:
dfCen['tUpdated'].C0.append(8)

In [36]:
dfCen['tUpdated'].apply(func=lambda x: tuple(x), )

C0    (4.5, 5.0, 2, 8)
C1       (5.0, 7.0, 2)
Name: tUpdated, dtype: object

In [40]:
dfCen['init'].apply(list.append, args=([32]))

C0    None
C1    None
Name: init, dtype: object

In [41]:
dfCen

                    init              tUpdated pUpdated
C0  [4.5, 5.0, 2, 8, 32]  [4.5, 5.0, 2, 8, 32]       ()
C1     [5.0, 7.0, 2, 32]     [5.0, 7.0, 2, 32]       ()

In [19]:
dfcl.where(cond=(dfcl == dfcl['asgPointsLtrs']),)

ValueError: Operands are not aligned. Do `left, right = left.align(right, axis=1, copy=False)` before operating.

---